# Generated by Django 6.0.4 on 2026-08-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
