# Generated by Django 6.0.4 on 2026-08-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_delivery_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='CLOSED', max_length=10)),
                ('market_date', models.DateField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_settings',
            },
        ),
        migrations.CreateModel(
            name='AdminWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='myapp.admin')),
            ],
            options={
                'db_table': 'admin_wallet',
            },
        ),
        migrations.CreateModel(
            name='FarmerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(db_column='farmer_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='myapp.farmer', to_field='farmer_id')),
            ],
            options={
                'db_table': 'farmer_wallet',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter'), ('Pieces', 'Pieces')], max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(db_column='farmer_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.farmer', to_field='farmer_id')),
                ('winning_customer', models.ForeignKey(blank=True, db_column='winning_customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_products', to='myapp.customer', to_field='customer_id')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='BargainingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('bid_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACCEPTED', 'ACCEPTED'), ('OUTBID', 'OUTBID')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='myapp.customer', to_field='customer_id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='myapp.product')),
            ],
            options={
                'db_table': 'bargaining_bid',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('winning_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('farmer_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admin_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.customer', to_field='customer_id')),
                ('farmer', models.ForeignKey(db_column='farmer_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='myapp.farmer', to_field='farmer_id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='myapp.product')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
