# Generated by Django 6.0.4 on 2026-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_marketsettings_adminwallet_farmerwallet_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Vegetable', max_length=100),
        ),
    ]
