# Generated by Django 6.0.4 on 2026-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsettings',
            name='bargaining_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('ACTIVE', 'ACTIVE'), ('STOPPED', 'STOPPED')], default='NOT_STARTED', max_length=15),
        ),
        migrations.AddField(
            model_name='marketsettings',
            name='product_registration_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='CLOSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='bargainingbid',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACCEPTED', 'ACCEPTED'), ('OUTBID', 'OUTBID'), ('REJECTED', 'REJECTED')], default='ACTIVE', max_length=20),
        ),
    ]
