# Generated by Django 6.0.4 on 2026-08-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_marketsettings_bargaining_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('SOLD', 'SOLD'), ('UNSOLD', 'UNSOLD')], default='AVAILABLE', max_length=20),
        ),
    ]
