# Generated by Django 6.0.4 on 2026-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_delivery_address_alter_delivery_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ASSIGNED', 'ASSIGNED'), ('PICKED_UP', 'PICKED_UP'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('AWAITING_CUSTOMER_CONFIRMATION', 'AWAITING_CUSTOMER_CONFIRMATION'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=50),
        ),
    ]
