# Generated by Django 6.0.4 on 2026-09-02 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_deliveryorder_customer_confirmation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED', 'ASSIGNED'), ('BUSY', 'BUSY')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('num_workers', models.PositiveIntegerField()),
                ('work_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('requested_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('WAGE_NEGOTIATION', 'WAGE_NEGOTIATION'), ('WAGE_AGREED', 'WAGE_AGREED'), ('WORKERS_ASSIGNED', 'WORKERS_ASSIGNED'), ('TASK_CREATED', 'TASK_CREATED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_requests', to='myapp.farmer')),
            ],
            options={
                'db_table': 'worker_request',
            },
        ),
        migrations.CreateModel(
            name='WorkerSalarySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('individual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_settlement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('PAID_TO_ADMIN', 'PAID_TO_ADMIN'), ('PAID', 'PAID')], default='PAYMENT_PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_settlements', to='myapp.farmer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_settlements', to='myapp.worker')),
                ('worker_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.workerrequest')),
            ],
            options={
                'db_table': 'worker_salary_settlement',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('WORKER_SALARY_PAYMENT', 'WORKER_SALARY_PAYMENT'), ('WALLET_TOPUP', 'WALLET_TOPUP'), ('WORKER_SALARY_DISBURSE', 'WORKER_SALARY_DISBURSE')], max_length=30)),
                ('prev_farmer_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_farmer_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prev_admin_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_admin_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='myapp.admin')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='myapp.farmer')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='myapp.worker')),
                ('worker_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='myapp.workersalarysettlement')),
            ],
            options={
                'db_table': 'wallet_transaction',
            },
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('work_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('AWAITING_FARMER_CONFIRMATION', 'AWAITING_FARMER_CONFIRMATION'), ('COMPLETED', 'COMPLETED')], default='ASSIGNED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_tasks', to='myapp.farmer')),
                ('worker_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='myapp.workerrequest')),
                ('workers', models.ManyToManyField(related_name='tasks', to='myapp.worker')),
            ],
            options={
                'db_table': 'worker_task',
            },
        ),
        migrations.AddField(
            model_name='workersalarysettlement',
            name='worker_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='myapp.workertask'),
        ),
        migrations.CreateModel(
            name='WorkerWageOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('offered_by', models.CharField(choices=[('FARMER', 'FARMER'), ('ADMIN', 'ADMIN')], max_length=10)),
                ('amount_per_worker_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_offers', to='myapp.workerrequest')),
            ],
            options={
                'db_table': 'worker_wage_offer',
            },
        ),
    ]
