# Generated by Django 6.0.4 on 2026-09-20 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_worker_status_workerrequest_workersalarysettlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargainingbid',
            name='farmer_bidder',
            field=models.ForeignKey(blank=True, db_column='farmer_bidder_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_as_farmer', to='myapp.farmer', to_field='farmer_id'),
        ),
        migrations.AddField(
            model_name='product',
            name='winning_farmer',
            field=models.ForeignKey(blank=True, db_column='winning_farmer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_products_as_farmer', to='myapp.farmer', to_field='farmer_id'),
        ),
        migrations.AddField(
            model_name='sale',
            name='farmer_customer',
            field=models.ForeignKey(blank=True, db_column='farmer_customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_as_customer', to='myapp.farmer', to_field='farmer_id'),
        ),
        migrations.AlterField(
            model_name='bargainingbid',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='myapp.customer', to_field='customer_id'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.customer', to_field='customer_id'),
        ),
    ]
