# Generated by Django 6.0.4 on 2026-09-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bargainingbid_farmer_bidder_product_winning_farmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('supply_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('available_quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplies/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='AVAILABLE', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_supply',
            },
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('WORKER_SALARY_PAYMENT', 'WORKER_SALARY_PAYMENT'), ('WALLET_TOPUP', 'WALLET_TOPUP'), ('WORKER_SALARY_DISBURSE', 'WORKER_SALARY_DISBURSE'), ('PURCHASE_FROM_ADMIN', 'Purchase from Admin'), ('FARM_SUPPLY_SALE', 'Farm Supply Sale')], max_length=30),
        ),
        migrations.CreateModel(
            name='SupplyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_purchases', to='myapp.farmer')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.adminsupply')),
            ],
            options={
                'db_table': 'supply_purchase',
            },
        ),
    ]
